function f_lsa(){
  lsd.exe -al
}


#ALIASES
Set-Alias -Name cat -Value bat.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name lsa -Value f_lsa -Scope "Global" -Option "AllScope"
Set-Alias -Name ls -Value lsd.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name htop -Value ntop -Scope "Global" -Option "AllScope"
Set-Alias -Name curl -Value curl.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name wget -Value wget.exe -Scope "Global" -Option "AllScope"
# COREUTLS ALIASES
Set-Alias -Name basename -Value basename.exe -Scope "Global" -Option "AllScope"
# Set-Alias -Name cat -Value cat.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name chmod -Value chmod.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name comm -Value comm.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name cp -Value cp.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name cut -Value cut.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name date -Value date.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name dirname -Value dirname.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name echo -Value echo.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name env -Value env.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name expr -Value expr.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name false -Value false.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name fold -Value fold.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name head -Value head.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name id -Value id.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name install -Value install.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name join -Value join.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name ln -Value ln.exe -Scope "Global" -Option "AllScope"
# Set-Alias -Name ls -Value ls.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name md5sum -Value md5sum.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name mkdir -Value mkdir.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name msysmnt -Value msysmnt.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name mv -Value mv.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name od -Value od.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name paste -Value paste.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name printf -Value printf.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name ps -Value ps.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name pwd -Value pwd.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name rm -Value rm.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name rmdir -Value rmdir.exe -Scope "Global" -Option "AllScope"
# Set-Alias -Name sleep -Value sleep.exe -Scope "Global" -Option "AllScope"
# Set-Alias -Name sort -Value sort.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name split -Value split.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name stty -Value stty.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name tail -Value tail.exe -Scope "Global" -Option "AllScope"
# Set-Alias -Name tee -Value tee.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name touch -Value touch.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name tr -Value tr.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name true -Value true.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name uname -Value uname.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name uniq -Value uniq.exe -Scope "Global" -Option "AllScope"
Set-Alias -Name wc -Value wc.exe -Scope "Global" -Option "AllScope"

#THEME
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\amro.omp.json" | Invoke-Expression
